[project]
name = "models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "auto-round>=0.9.7",
    "intel-extension-for-pytorch>=2.5",
    "optimum[openvino]>=2.1.0",
    "torch<2.9",
]
